version: '2'

networks:
  default:
    name: APIGateWay

services:
  api:
    ports:
      - "10550:10550"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: APIGateWay
  
